"""SQLModel tables (`docs/data-model.md` -> Conversation and judge state,
Audit data).

M1 scope only: `conversation`, `message`, `audit_event` (data-model.md ->
Migration approach -> Sequencing: "M1's initial migration creates
`conversation`, `message`, and `audit_event`"). Every other table in
`data-model.md` arrives with the milestone that needs it, in its own
migration.

Primary keys are UUIDs generated by the application (data-model.md ->
Conventions), so every `id` column uses `default_factory=uuid.uuid4` rather
than a server-side default.
"""

import uuid
from datetime import UTC, datetime

from sqlalchemy import CheckConstraint, Column, DateTime, Index, UniqueConstraint, func, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlmodel import Field, SQLModel


def _utcnow() -> datetime:
    return datetime.now(UTC)


class Conversation(SQLModel, table=True):
    """`docs/data-model.md` -> Conversation and judge state -> `conversation`."""

    __tablename__ = "conversation"
    __table_args__ = (Index("ix_conversation_updated_at", text("updated_at DESC")),)

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4, primary_key=True, sa_type=PGUUID(as_uuid=True)
    )
    title: str | None = Field(default=None)
    summary: str | None = Field(default=None)
    summary_through_seq: int | None = Field(default=None)
    created_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False, server_default=func.now()),
    )
    # Bumped on every new message (PRD WP2 checklist); `onupdate` covers any
    # UPDATE of this row as a backstop even if a caller forgets to set it
    # explicitly.
    updated_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(
            DateTime(timezone=True),
            nullable=False,
            server_default=func.now(),
            onupdate=func.now(),
        ),
    )


class Message(SQLModel, table=True):
    """`docs/data-model.md` -> Conversation and judge state -> `message`."""

    __tablename__ = "message"
    __table_args__ = (
        UniqueConstraint("conversation_id", "seq", name="uq_message_conversation_id_seq"),
        CheckConstraint("role in ('user','assistant','tool')", name="ck_message_role"),
    )

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4, primary_key=True, sa_type=PGUUID(as_uuid=True)
    )
    conversation_id: uuid.UUID = Field(
        foreign_key="conversation.id",
        ondelete="CASCADE",
        nullable=False,
        sa_type=PGUUID(as_uuid=True),
    )
    seq: int = Field(nullable=False)
    turn_id: uuid.UUID = Field(nullable=False, sa_type=PGUUID(as_uuid=True))
    role: str = Field(nullable=False)
    content: str = Field(nullable=False)
    payload: dict | None = Field(default=None, sa_column=Column(JSONB, nullable=True))
    route: str | None = Field(default=None)
    created_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False, server_default=func.now()),
    )


class AuditEvent(SQLModel, table=True):
    """`docs/data-model.md` -> Audit data -> `audit_event`."""

    __tablename__ = "audit_event"
    __table_args__ = (
        CheckConstraint("severity in ('info','warning','error')", name="ck_audit_event_severity"),
        Index("ix_audit_event_conversation_id_created_at", "conversation_id", "created_at"),
        Index("ix_audit_event_event_type_created_at", "event_type", "created_at"),
    )

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4, primary_key=True, sa_type=PGUUID(as_uuid=True)
    )
    conversation_id: uuid.UUID | None = Field(
        default=None,
        foreign_key="conversation.id",
        ondelete="CASCADE",
        sa_type=PGUUID(as_uuid=True),
    )
    turn_id: uuid.UUID | None = Field(default=None, sa_type=PGUUID(as_uuid=True))
    event_type: str = Field(nullable=False)
    severity: str = Field(nullable=False)
    details: dict = Field(
        default_factory=dict,
        sa_column=Column(JSONB, nullable=False, server_default=text("'{}'::jsonb")),
    )
    created_at: datetime = Field(
        default_factory=_utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False, server_default=func.now()),
    )
